SchoollManagementSystem/Controllers/StudentController.cs
using SMS.Data;
using SMS.Entities;
using SMS.services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace SchoollManagementSystem.Controllers
{

    public class StudentController : Controller

    {
        setVoucherpercentservice setVoucherpercentservice = new setVoucherpercentservice();
        StudentCurrentStatuseservice StudentCurrentStatuseservice = new StudentCurrentStatuseservice();
        classesStudentMappingservice classesStudentMappingservice = new classesStudentMappingservice();
        AuthorityDetailTblservice AuthorityDetailTblservice = new AuthorityDetailTblservice();
        Branchservice branchservice = new Branchservice();
        sectionservice sectionservice = new sectionservice();
        Sessionservice sessionservice = new Sessionservice();
        Termservice termservice = new Termservice();
        Studentservice studentservice = new Studentservice();
        Categoryservice categoryservice = new Categoryservice();
        Programdegreesservice programdegreesservice = new Programdegreesservice();


        classservice classservice = new classservice();


        classservice Classservice = new classservice();

       
        

        public JsonResult uploadpics(allpics allpics)
        {
            var piclist = new List<allpics>();

            JsonResult objjson = new JsonResult();
            var files = Request.Files;
            for (int i = 0; i < files.Count; i++)
            {
                var picfile = files[i];
                var pathimages = Server.MapPath("~/images/");
                var filenames = Guid.NewGuid() + Path.GetExtension(picfile.FileName);
                var fileName = pathimages + filenames;
                picfile.SaveAs(fileName);
                allpics.url = filenames;
                
            }
            piclist.Add(allpics);
            objjson.Data = piclist;
            var _context = new SMSContext();
            _context.allpics.Add(allpics);
            _context.SaveChanges();
            return objjson;


        }
        public ActionResult AddStudent()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddStudent(Student Student)
        {
            if (Student.imagefile != null)
            {
                string filename = Path.GetFileNameWithoutExtension(Student.imagefile.FileName);
                string extentsion = Path.GetExtension(Student.imagefile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extentsion;
                Student.Admissionimage = "~/images/" + filename;
                filename = Path.Combine(Server.MapPath("/images/"), filename);
                Student.imagefile.SaveAs(filename);
                Studentservice studentservice = new Studentservice();
                studentservice.savestudent(Student);

            }
            else

            {

                Student.Admissionimage = "download.png";


           

            Studentservice service = new Studentservice();
            service.savestudent(Student);
            }
            return RedirectToAction("AssignClass", new { studentroll = Student.RollNo, id = Student.ID });







        }

        //download file code

        public ActionResult imagedetails(int id)
        {

            Student s = studentservice.getbyid(id);
            return View(s);


        }

        //public ActionResult downloadfile(int a)
        //{
        //    var getimage = studentservice.getbyid(a);
        //    Student student = new Student();
        //  var   stgimg = student.Admissionimage;
        //    string path = Server.MapPath("~stgimg");
        //    return View(); 

        //}
        public ActionResult EditStudent(int id)
        {
            Studentservice service = new Studentservice();
            var Student = service.getbyid(id);
            TempData["imgpath"] = Student.Admissionimage;
            return View(Student);
        }
        [HttpPost]
        public ActionResult EditStudent(Student Student)
        {
            if (Student.imagefile != null)
            {
                string filename = Path.GetFileNameWithoutExtension(Student.imagefile.FileName);
                string extentsion = Path.GetExtension(Student.imagefile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extentsion;
                Student.Admissionimage = "~/images/" + filename;
                filename = Path.Combine(Server.MapPath("/images/"), filename);
                Student.imagefile.SaveAs(filename);
                Studentservice service = new Studentservice();
                service.updateStudent(Student);

            }
            else
            {


                Student.Admissionimage = TempData["imgpath"].ToString();

                Studentservice service = new Studentservice();
                service.updateStudent(Student);

            }
            return RedirectToAction("Studentslist");
        }
        public ActionResult AdmissionForm()
        {
            return View();

        }
        //public ActionResult Assignbranch(string id)
        //{
        //    Branchservice branchservice = new Branchservice();
        //    Studentservice studentservice = new Studentservice();
        //   
        //var emp   = studentservice.getstudent().Where(x => x.RollNo == id).SingleOrDefault();

        // ViewBag.getclass = Classservice.getclasses().ToList();
        //    ViewBag.branchlist = branchservice.getbranch().ToList();
        //    return View(emp);

        //}
        //[HttpPost]
        //public ActionResult Assignbranch(FormCollection fc,string id)


        //{
        //    StudentBranchMapping studentBranchMapping = new StudentBranchMapping();
        //    var classesid= (fc["cboclass"]);
        //    studentBranchMapping.BranchID=Convert.ToInt32((fc["cboBracnh"]));
        //    studentBranchMapping.StudentID = id;
        //    StudentBranchMappingBranchMappingservice studentBranchMappingBranchMappingservice = new StudentBranchMappingBranchMappingservice();
        //    studentBranchMappingBranchMappingservice.saveStudentBranchMapping(studentBranchMapping);
        //    return RedirectToAction("AssignClass",new {classid=classesid , id = studentBranchMapping.StudentID });




        //}
        public ActionResult AssignClass(string studentroll, int id)
        {

            var emp = studentservice.getstudent().Where(x => x.ID == id).SingleOrDefault();
            ViewBag.session = sessionservice.getsession().ToList();
            ViewBag.section = sectionservice.getsection().ToList();
            ViewBag.termname = termservice.getTerm().ToList();
            ViewBag.getclass = Classservice.getclasses().ToList();
            ViewBag.branchlist = branchservice.getbranch().ToList();
            ViewBag.catlist = categoryservice.getCategory().ToList();
            ViewBag.program = programdegreesservice.getProgramdegree().ToList();

            return View(emp);

        }
        [HttpPost]
        public ActionResult AssignClass(FormCollection fc, string studentroll, int id)
        {
            string check =( fc["checkbox"]);
            
            if (check=="on")
            {
                StudentCurrentStatus studentCurrentStatus = new StudentCurrentStatus();

                studentCurrentStatus.StudentID = id;
                studentCurrentStatus.BranchID = fc["cboBracnh"];
                studentCurrentStatus.classesID = Convert.ToInt32((fc["cboclass"]));
                studentCurrentStatus.CategoryID = Convert.ToInt32((fc["cbocategory"]));
                studentCurrentStatus.SessionID = Convert.ToInt32((fc["cbosession"]));
                studentCurrentStatus.TermID = Convert.ToInt32((fc["cboterm"]));
                studentCurrentStatus.SectionID = Convert.ToInt32((fc["cbosection"]));
                studentCurrentStatus.ProgramdegreeID = Convert.ToInt32(fc["cboprogram"]);
                StudentCurrentStatuseservice studentCurrentStatuseservice = new StudentCurrentStatuseservice();
                studentCurrentStatuseservice.saveStudentCurrentStatus(studentCurrentStatus);


                return RedirectToAction("DiscountDetails", new
                {

                    stid = studentCurrentStatus.StudentID,
                    branchid = studentCurrentStatus.BranchID,
                    classid = studentCurrentStatus.classesID,
                    sessionid = studentCurrentStatus.SessionID,
                    cateid = studentCurrentStatus.CategoryID,
                    sectionid = studentCurrentStatus.SessionID,
                    Termid = studentCurrentStatus.TermID,
                    feevtype = 1
                });

            }
            else
            {
                StudentCurrentStatus studentCurrentStatus = new StudentCurrentStatus();

                studentCurrentStatus.StudentID = id;
                studentCurrentStatus.BranchID = fc["cboBracnh"];
                studentCurrentStatus.classesID = Convert.ToInt32((fc["cboclass"]));
                studentCurrentStatus.CategoryID = Convert.ToInt32((fc["cbocategory"]));
                studentCurrentStatus.SessionID = Convert.ToInt32((fc["cbosession"]));
                studentCurrentStatus.TermID = Convert.ToInt32((fc["cboterm"]));
                studentCurrentStatus.SectionID = Convert.ToInt32((fc["cbosection"]));
                studentCurrentStatus.ProgramdegreeID = Convert.ToInt32(fc["cboprogram"]);

                StudentCurrentStatuseservice studentCurrentStatuseservice = new StudentCurrentStatuseservice();
                studentCurrentStatuseservice.saveStudentCurrentStatus(studentCurrentStatus);


                return RedirectToAction("Studentsclasslist");


            }



        }
        

SchoollManagementSystem/Controllers/setvpercentController.cs
using SMS.Entities;
using SMS.services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoollManagementSystem.Controllers
{
    public class setvpercentController : Controller
    {
        setVoucherpercentservice setVoucherpercentservice = new setVoucherpercentservice();
        // GET: setvpercent
        public ActionResult updateVPercent(int id)
        {
            
            var list=setVoucherpercentservice.getbyid(id);



            return View(list);
        }
        [HttpPost]
        public ActionResult updateVPercent(setVoucherpercent setVoucherpercent)
        {

            setVoucherpercentservice.updatesetVoucherpercent(setVoucherpercent);

            return View();
        }
    }
}

SchoollManagementSystem/Views/Student/AlreadyDiscount.cshtml
@{
    ViewBag.Title = "AlreadyDiscount";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>Already Exsist Record Please Update Recored</h2>

SchoollManagementSystem/Views/Student/EditStudent.cshtml
@model SMS.Entities.Student

@{
    ViewBag.Title = "EditStudent";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>EditStudent</h2>

@using (Html.BeginForm("EditStudent", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.RollNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RollNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RollNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.whatsappNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whatsappNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whatsappNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdmissionFormNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdmissionFormNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdmissionFormNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dateofbirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dateofbirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dateofbirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdmissionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdmissionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdmissionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Admissionimage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.Admissionimage)" height="70 " width="150" >
                     <input type="file" name="imagefile"  class="form-control">
                @Html.ValidationMessageFor(model => model.Admissionimage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SchoollManagementSystem/Views/Student/Finepromotionlist.cshtml
@{
    ViewBag.Title = "SearchClassstatus";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>Find Class For Promotion</h2>

<div class="heading-layout1">
    <div class="item-title">
        <h3> @ViewBag.mainheading </h3>
    </div>

</div>

<br />

<form class="new-added-form" action="@Url.Action("studentsPromotion","Student")" target="_blank">
    <div class="row ">

        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Class*</label>
            @Html.DropDownList("cboclass", new SelectList(ViewBag.getclass, "id", "classname"), "Select Any one", new { @class = "form-control"  ,required = "required" })
       
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Session *</label>
            @Html.DropDownList("cbosession", new SelectList(ViewBag.session, "ID", "Sessionname"), "Select Any one", new { @class = "form-control", required = "required" })

        </div>

        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select category *</label>
            @Html.DropDownList("cbocategory", new SelectList(ViewBag.catlist, "id", "CategoryName "), "Select Any one", new { @class = "form-control", required = "required" })

        </div>

        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label> Select Semester  *</label>
            @Html.DropDownList("cboterm", new SelectList(ViewBag.termname, "id", "TermName"), "Select Any one", new { @class = "form-control", required = "required" })


        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Section</label>
            @Html.DropDownList("cbosection", new SelectList(ViewBag.section, "id", "sectionName"), "Select Any one", new { @class = "form-control", required = "required" })
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Program</label>
            @Html.DropDownList("cboprogram", new SelectList(ViewBag.programall, "id", "Pname"), "Select Any one", new { @class = "form-control", required = "required" })
        </div>
      

        @*<div class="col-lg-6 col-12 form-group mg-t-30">
                <label class="text-dark-medium">Upload Student Photo (150px X 150px)</label>
                <input type="file" class="form-control-file">
            </div>*@
        <div class="col-12 form-group mg-t-8">
            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Submit</button>

        </div>
    </div>
</form>

SchoollManagementSystem/Views/Student/Studentsclasslist.cshtml
@model IEnumerable<SMS.Entities.StudentDisplayVM>

@{
    ViewBag.Title = "Studentsclasslist";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Students-List</title>
</head>
<body>
        
    <table class="table table  table-bordered" id="myTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Student.RollNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Student.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Classes.classname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.session.Sessionname)

                </th>

                <th>
                    @Html.DisplayNameFor(model => model.section.sectionName)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.term.TermName)
                </th>



                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.RollNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Classes.classname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.session.Sessionname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.section.sectionName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.term.TermName)
                </td>


                <td>

                    <a href="@Url.Action("Editclasses","student" , new { id = item.StudentCurrentStatus.id })" class="btn btn-danger">
                        <span class="fas fa-edit mr-2"></span>

                    </a>

                    @*<a href="@Url.Action("DiscountDetails","student" , new { stid = item.StudentCurrentStatus.StudentID,branchid=item.StudentCurrentStatus.BranchID,classid=item.StudentCurrentStatus.classesID,
               sessionid=item.StudentCurrentStatus.SessionID,cateid=item.StudentCurrentStatus.CategoryID,sectionid=item.StudentCurrentStatus.SectionID,Termid=item.StudentCurrentStatus.TermID,feevtype=1 })" class="btn btn-danger">
                <span class="fas fa-percent mr-2"></span>

            </a>*@

                    <a href="@Url.Action("Deleteclasses","student" , new { id = item.StudentCurrentStatus.id })" class="btn btn-danger">
                        <span class="fas fa-list mr-2"></span>

                    </a>




                    <a href="@Url.Action("updateVPercent","setvpercent" , new { id = item.SetVoucherpercent.id })" class="btn btn-danger">
                        <span class="fas fa-percent mr-2"></span>

                    </a>


                    <a href="~/feesV.aspx?id=@item.Student.ID&termid=@item.StudentCurrentStatus.TermID" class="btn btn-success"><span class="fa fa-print"> P1 </span></a>
                    <a href="~/reportsform/VoucherV1.aspx?id=@item.Student.ID&termid=@item.StudentCurrentStatus.TermID" class="btn btn-primary"><span class="fa fa-print"> P1 A </span></a>
                    <a href="~/reportsform/VoucherV2.aspx?id=@item.Student.ID&termid=@item.StudentCurrentStatus.TermID" class="btn btn-primary"><span class="fa fa-print"> P1 B </span></a>
                    <a href="~/reportsform/VoucherV4.aspx?id=@item.Student.ID&termid=@item.StudentCurrentStatus.TermID" class="btn btn-success"><span class="fa fa-print"> C1 </span></a>


                    <a href="~/fineHead/Index?StudentID=@item.StudentCurrentStatus.StudentID&vid=1&bid=@item.StudentCurrentStatus.BranchID&cid=@item.StudentCurrentStatus.classesID&pid=@item.StudentCurrentStatus.ProgramdegreeID&seid=@item.StudentCurrentStatus.SessionID&ctid=@item.StudentCurrentStatus.CategoryID&secid=@item.StudentCurrentStatus.SectionID&trid=@item.StudentCurrentStatus.TermID" class="btn btn-success"><span class="fa fa-print"> Add-FineV1 </span></a>
                    <a href="~/fineHead/Index?StudentID=@item.StudentCurrentStatus.StudentID&vid=2&bid=@item.StudentCurrentStatus.BranchID&cid=@item.StudentCurrentStatus.classesID&pid=@item.StudentCurrentStatus.ProgramdegreeID&seid=@item.StudentCurrentStatus.SessionID&ctid=@item.StudentCurrentStatus.CategoryID&secid=@item.StudentCurrentStatus.SectionID&trid=@item.StudentCurrentStatus.TermID" class="btn btn-success"><span class="fa fa-print"> Add-FineV4 </span></a>
                </td>
            </tr>
            }
        </tbody>
    </table>

</body>
</html>
@section scripts
{

    <script>
      $(document).ready(function () {
          $('#myTable').DataTable();
      });</script>
}

SchoollManagementSystem/Views/Student/Studentslist.cshtml
@model IEnumerable<SMS.Entities.Student>

@{
    ViewBag.Title = "Studentslist";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>Studentslist</h2>

<p>
    @Html.ActionLink("Create", "AddStudent", null,new { @class = "btn btn-primary" })
</p>
<table class="table table-striped table-bordered " id="Table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RollNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <th>
                <label>AdmissionNo</label>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RollNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.AdmissionFormNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>



            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>

                <a href="@Url.Action("EditStudent","student" , new { id = item.ID })" class="btn btn-danger">
                    <span class="fas fa-edit mr-2"></span>

                </a>
                |
                <a href="@Url.Action("EditStudent","student" , new { id = item.ID })" class="btn btn-danger">
                    <span class="fas fa-trash mr-2"></span>

                </a>
                |
                <a href="@Url.Action("EditStudent","student" , new { id = item.ID })" class="btn btn-danger">
                    <span class="fas fa-list mr-2"></span>

                </a>


                |
                <a href="@Url.Action("imagedetails","Student" , new { id = item.ID })" class="btn btn-danger">
                    <span class="fas fa-image mr-2"></span>

                </a>
            </td>
          
        </tr>
        }
    </tbody>

</table>

@section scripts
{

    <script>
      $(document).ready(function () {
          $('#Table').DataTable();
      });</script>
}

SchoollManagementSystem/Views/Student/allsemesterRecords.cshtml
@{
    ViewBag.mainheading = "All Semester Record";
}


<form class="new-added-form" method="get" action="@Url.Action("allsemesterRecord","Student")">
    <div class="row ">
       
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Class*</label>
            @Html.DropDownList("cboclass", new SelectList(ViewBag.getclass, "id", "classname"), "Select Any one", new { @class = "form-control" })
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Session *</label>
            @Html.DropDownList("cbosession", new SelectList(ViewBag.session, "ID", "Sessionname"), "Select Any one", new { @class = "form-control" })

        </div>

       

        @*<div class="col-lg-6 col-12 form-group mg-t-30">
                <label class="text-dark-medium">Upload Student Photo (150px X 150px)</label>
                <input type="file" class="form-control-file">
            </div>*@
        <div class="col-12 form-group mg-t-8">
            <button type="submit" id="btn1" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Next</button>

           
        </div>

    </div>
</form>



<!-- Admit Form Area End Here -->

SchoollManagementSystem/Views/Student/feespackage.cshtml
@{
    ViewBag.Title = "feespackage";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>feespackage</h2>

SchoollManagementSystem/Views/Student/imagedetails.cshtml
@model SMS.Entities.Student

@{
    ViewBag.Title = "Admission form image";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>imagedetails</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RollNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RollNo)
        </dd>

      
        <dt>
            @Html.DisplayNameFor(model => model.AdmissionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdmissionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admissionimage)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Admissionimage)" height="500" width="1000">
        </dd>

        

    </dl>
</div>