SchoollManagementSystem/Controllers/HeadController.cs
using SMS.Entities;
using SMS.services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoollManagementSystem.Controllers
{
    public class HeadController : Controller
    {
        // GET: Head

        public ActionResult Mheadlist()

        { 
            MHeadCodeservice mHeadCodeservice = new MHeadCodeservice();
          var list = mHeadCodeservice.getMHeadCode().ToList();
            return View(list);
        }
        public ActionResult addhead()

        {

            return View();
        }
        [HttpPost]
        public ActionResult addhead(MHeadCode mHeadCode)

        {
            MHeadCodeservice mHeadCodeservice = new MHeadCodeservice();
            mHeadCodeservice.saveMHeadCode(mHeadCode);

            return View("Mheadlist");
        }
        public ActionResult updatehead(int id)

        {
            MHeadCodeservice mHeadCodeservice = new MHeadCodeservice();
           var data= mHeadCodeservice.getbyid(id);


            return View(data);
        }
        [HttpPost]
        public ActionResult updatehead(MHeadCode mHeadCode)

        {
            MHeadCodeservice mHeadCodeservice = new MHeadCodeservice();
            mHeadCodeservice.updateMHeadCode(mHeadCode);
            return RedirectToAction("Mheadlist");
        }





    }

}

SchoollManagementSystem/Views/Head/Mheadlist.cshtml
@model IEnumerable<SMS.Entities.MHeadCode>

@{
    ViewBag.Title = "Mheadlist";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>Mhead_Details</h2>

<p>
    @Html.ActionLink("Create New", "addhead", null,new { @class = "btn btn-primary" })
</p>
<table class="table table  table-bordered" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>

            <th>Action</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            
            <td>

                <a href="@Url.Action("updatehead","Head" , new {  id = item.MainHeadCode })" class="btn btn-danger">
                    <span class="fas fa-edit mr-2"></span>

                </a>
                |
                <a href="@Url.Action("updatehead","Head" , new {   id = item.MainHeadCode})" class="btn btn-danger">
                    <span class="fas fa-trash mr-2"></span>

                </a>
                |
                <a href="@Url.Action("updatehead","Head"  , new {    id = item.MainHeadCode})" class="btn btn-danger">
                    <span class="fas fa-list mr-2"></span>

                </a>



            </td>
        </tr>
        }
    </tbody>
</table>

@section scripts
{

    <script>
      $(document).ready(function () {
          $('#myTable').DataTable();
      });</script>
}

SchoollManagementSystem/Views/Head/addhead.cshtml
<!-- Breadcubs Area Start Here -->
@{
    ViewBag.mainheading = "Mhead";
}

<!-- Breadcubs Area End Here -->
<!-- Add Class Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>Add New @ViewBag.mainheading</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button"
                   data-toggle="dropdown" aria-expanded="false">...</a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                </div>
            </div>
        </div>
        <form class="new-added-form" method="post" autocomplete="on">
            <div class="row">
                @*<div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Branch Code *</label>
                        <input type="text" placeholder="Enter branch Code" name="branchcode" class="form-control">
                    </div>*@
                <div class="col-xl-3 col-lg-6 col-12 form-group">
                    <label>MheadName</label>
                    <input type="text" placeholder="Enter Mhead Name" name="Description" class="form-control">
                </div>

                <div class="col-md-6 form-group"></div>
                <div class="col-12 form-group mg-t-8">
                    <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                    <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Add Class Area End Here -->

SchoollManagementSystem/Views/Head/updatehead.cshtml
@model SMS.Entities.MHeadCode

@{
    ViewBag.mainheading = "Mhead";
}




<div class="item-title">
    <h3>Add New @ViewBag.mainheading</h3>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MainHeadCode)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="update" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>