SchoollManagementSystem/Controllers/RecordheadController.cs
using SMS.Entities;
using SMS.services;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Data;

namespace SchoollManagementSystem.Controllers
{
    public class RecordheadController : Controller
    {
        StudentCurrentStatuseservice StudentCurrentStatuseservice = new StudentCurrentStatuseservice();
        classesStudentMappingservice classesStudentMappingservice = new classesStudentMappingservice();
        Branchservice branchservice = new Branchservice();
        sectionservice sectionservice = new sectionservice();
        FeeVoucherType FeeVoucherType = new FeeVoucherType();
        Sessionservice sessionservice = new Sessionservice();
        Termservice termservice = new Termservice();
        Studentservice studentservice = new Studentservice();
        Categoryservice categoryservice = new Categoryservice();
        classservice classservice = new classservice();
        FeeVoucherTypeservice FeeVoucherTypeservice = new FeeVoucherTypeservice();
        Programdegreesservice programdegreesservice = new Programdegreesservice();
      
       SubHead3Codeservice subHead3Codeservice= new SubHead3Codeservice();

        // GET: Recordhead
        public ActionResult Index()
        {
            ViewBag.session = sessionservice.getsession().ToList();
            ViewBag.section = sectionservice.getsection().ToList();
            ViewBag.termname = termservice.getTerm().ToList();
            ViewBag.getclass = classservice.getclasses().ToList();
            ViewBag.branchlist = branchservice.getbranch().ToList();
            ViewBag.catlist = categoryservice.getCategory().ToList();
            ViewBag.programall = programdegreesservice.getProgramdegree().ToList();
            ViewBag.head = subHead3Codeservice.getSubHead3Code().ToList();
            ViewBag.headv = FeeVoucherTypeservice.getFeeVoucherType().ToList();
            return View();
        }
        public ActionResult FindByHead(int? cboclass, int? cbosession,int? cbovoucher, int? cbocategory, int? cboterm, int? cbosection,
            int? cboprogram, int? cbohead,DateTime start,DateTime  End)
        {
            
            SMSContext SMSContext = new SMSContext();
            ViewBag.classname = classservice.getclasses().Where(y => y.ID == cboclass).Select(x => x.classname).SingleOrDefault();
            ViewBag.session = sessionservice.getsession().Where(y => y.ID == cbosession).Select(x => x.Sessionname).SingleOrDefault();
            ViewBag.cat = categoryservice.getCategory().Where(y => y.id == cbocategory).Select(x => x.CategoryName).SingleOrDefault();
            ViewBag.sems = termservice.getTerm().Where(y => y.id == cboterm).Select(x => x.TermName).SingleOrDefault();
            ViewBag.section = sectionservice.getsection().Where(y => y.id == cbosection).Select(x => x.sectionName).SingleOrDefault();
            ViewBag.startdata = start;
            ViewBag.enddata = End;
            

           
            SqlParameter starts = new SqlParameter("@start",start);
            SqlParameter ends = new SqlParameter("@end", End);
            SqlParameter classids = new SqlParameter("@classid", cboclass);
            SqlParameter type = new SqlParameter("@type", cbovoucher);
            SqlParameter sids = new SqlParameter("@seid", cbosession);
            SqlParameter tids = new SqlParameter("@smid", cboterm);
            SqlParameter secs = new SqlParameter("@secid", cbosection);
            SqlParameter pid = new SqlParameter("@pid ", cboprogram);
            SqlParameter hid = new SqlParameter("@hid",cbohead);
            SqlParameter cid = new SqlParameter("@cid", cbocategory);

            ViewBag.name = "cboclass=" + cboclass + "&" + "cbosession=" + cbosession + "&" + "cbovoucher=" + cbovoucher + "&" + "cbocategory=" + cbocategory + "&" + "cboterm=" + cboterm + "&" + "cbosection=" + cbosection  + "&"+ "cboprogram=" + cboprogram+"&"+"cbohead="+cbohead+"&"+"start="+start+"&"+"End="+End;
            var list = SMSContext.Database.SqlQuery<vocuherheadvm>("getresultbyhead @classid,@seid,@type,@smid,@secid,@pid,@hid,@cid,@start,@end", classids, sids, type,tids, secs, pid, hid,cid,starts,ends).ToList();

       
            return View(list);
        }


    }
}

SchoollManagementSystem/Views/Recordhead/FindByHead.cshtml
@model IEnumerable<SMS.Entities.vocuherheadvm>

@{
    ViewBag.Title = "FindByHead";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>FindByHead</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @if (Model.ToList() == null)
    {



    }
</p>
<div class=" well container-fluid">
    <table class=" well row">
        <tr>
            <td><b>Class Name:</b></td>
            <td>@ViewBag.classname </td>

        </tr>
        <tr>
            <td><b> Session:</b></td>
            <td>@ViewBag.session</td>

        </tr>
        <tr>
            <td><b> Category:</b></td>
            <td>@ViewBag.cat </td>

        </tr>
        <tr>
            <td><b> Semester:</b></td>
            <td>@ViewBag.sems </td>

        </tr>
        <tr>
            <td><b>Section:</b></td>
            <td>@ViewBag.section </td>

        </tr>
         
        <tr>
            <td><b> Start date</b></td>
            <td>@ViewBag.startdata </td>

        </tr>
        <tr>
            <td><b>End date</b></td>
            <td>@ViewBag.enddata </td>

        </tr>




    </table>
</div>
<a href="/reportsform/HeadDetails.aspx?@ViewBag.name" class="btn btn-success">
    <span class="fa fa-print">Print</span>

</a>
<table class="table table table-bordered" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RollNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepositeDate)
            </th>
            <th>

                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VoucherNO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HeadValue)
            </th>

            <th>
                <label>Status</label>
            </th>
            <th></th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RollNo)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepositeDate)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VoucherNO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HeadValue)

            </td>

            <td>
                <label>Paid</label>

            </td>
            <td></td>
        </tr>
        }
    </tbody>
</table>
@section scripts
{

    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });</script>}

SchoollManagementSystem/Views/Recordhead/Index.cshtml
@{
    ViewBag.Title = "SearchClassstatus";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>Find-Class-status</h2>

<div class="heading-layout1">
    <div class="item-title">
        <h3> @ViewBag.mainheading </h3>
    </div>

</div>

<br />


<form class="new-added-form" action="@Url.Action("FindByHead","Recordhead")" target="_blank">
    <div class="row ">

        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Class*</label>
            @Html.DropDownList("cboclass", new SelectList(ViewBag.getclass, "id", "classname"), "Select Any one", new { @class = "form-control" })
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Session *</label>
            @Html.DropDownList("cbosession", new SelectList(ViewBag.session, "ID", "Sessionname"), "Select Any one", new { @class = "form-control" })

        </div>

        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select category *</label>
            @Html.DropDownList("cbocategory", new SelectList(ViewBag.catlist, "id", "CategoryName "), "Select Any one", new { @class = "form-control" })

        </div>

        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label> Select Semester  *</label>
            @Html.DropDownList("cboterm", new SelectList(ViewBag.termname, "id", "TermName"), "Select Any one", new { @class = "form-control" })


        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Section</label>
            @Html.DropDownList("cbosection", new SelectList(ViewBag.section, "id", "sectionName"), "Select Any one", new { @class = "form-control" })
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Program</label>
            @Html.DropDownList("cboprogram", new SelectList(ViewBag.programall, "id", "Pname"), "Select Any one", new { @class = "form-control" })
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Voucher</label>
            @Html.DropDownList("cbovoucher", new SelectList(ViewBag.headv, "FeeVoucherTypeCode", "feeVoucherType"), "Select Any one", new { @class = "form-control" })
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Head</label>
            @Html.DropDownList("cbohead", new SelectList(ViewBag.head, "SubHeadCode3", "Description"), "Select Any one", new { @class = "form-control" })
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select Start Date</label>
            <input type="date" class="form-control" name="start" required />
        </div>
        <div class="col-xl-3 col-lg-6 col-12 form-group">
            <label>Select End Date</label>
            <input type="date" class="form-control" name="End" required />
        </div>

        @*<div class="col-lg-6 col-12 form-group mg-t-30">
            <label class="text-dark-medium">Upload Student Photo (150px X 150px)</label>
            <input type="file" class="form-control-file">
        </div>*@
        <div class="col-12 form-group mg-t-8">
            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Submit</button>

        </div>
    </div>
</form>