SchoollManagementSystem/Controllers/TermController.cs
using SMS.Entities;
using SMS.services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoollManagementSystem.Controllers
{
    public class TermController : Controller
    {
        // GET: Term
        public ActionResult listingTerm()
        {
            Termservice Termservice = new Termservice();
            var listTerms = Termservice.getTerm();
            return View(listTerms);
        }
        public ActionResult AddTerm()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddTerm(Term Term)
        {
            Termservice service = new Termservice();
            service.saveTerm(Term);
            return View();
        }
        public ActionResult EditTerm(int id)
        {
            Termservice service = new Termservice();
            var Term = service.getbyid(id);
            return View(Term);
        }
        [HttpPost]
        public ActionResult EditTerm(Term Term)
        {
            Termservice service = new Termservice();
            service.updateTerm(Term);
            return View("AddTerm");
        }
    }
}

SchoollManagementSystem/Views/Term/AddTerm.cshtml
<!-- Breadcubs Area Start Here -->
@{
    ViewBag.mainheading = "Semester";
}

<!-- Breadcubs Area End Here -->
<!-- Add Class Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>Add New @ViewBag.mainheading</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button"
                   data-toggle="dropdown" aria-expanded="false">...</a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                </div>
            </div>
        </div>
        <form class="new-added-form" method="post" autocomplete="on">
            <div class="row">
                <div class="col-xl-3 col-lg-6 col-12 form-group">
                    <label>Semester Name *</label>
                    <input type="text" placeholder="Enter Term Name" name="TermName" class="form-control">
                </div>
                @*<div class="col-xl-3 col-lg-6 col-12 form-group">
                    <label>Term Description</label>
                    <input type="text" placeholder="Enter Term Description " name="TermDescription" class="form-control">
                </div>*@

                <div class="col-md-6 form-group"></div>
                <div class="col-12 form-group mg-t-8">
                    <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                    <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Add Class Area End Here -->

SchoollManagementSystem/Views/Term/EditTerm.cshtml
@model SMS.Entities.Term
@{
    ViewBag.mainheading = "EditSemester";
}

<!-- Breadcubs Area End Here -->
<!-- Add Class Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>Add New @ViewBag.mainheading</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button"
                   data-toggle="dropdown" aria-expanded="false">...</a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                </div>
            </div>
        </div>
        <form class="new-added-form" method="post" autocomplete="on">
            <div class="row">
                <div class="col-xl-3 col-lg-6 col-12 form-group">
                    <label>Semester Name *</label>
                    <input type="text" placeholder="Enter Section Name" name="TermName" value="@Model.TermName" class="form-control">
                </div>
                @*<div class="col-xl-3 col-lg-6 col-12 form-group">
                    <label>Term Description</label>*@
                    <input type="hidden" placeholder="Enter Section Description " name="TermDescription" value="@Model.TermDescription" class="form-control">
                @*</div>*@

                <div class="col-md-6 form-group"></div>
                <div class="col-12 form-group mg-t-8">
                    <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Updates</button>
                    <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Add Class Area End Here -->

SchoollManagementSystem/Views/Term/listingTerm.cshtml
@model IEnumerable<SMS.Entities.Term>

@{
    ViewBag.Title = "Semester";
    Layout = "~/Views/Shared/_Layout_New.cshtml";
}

<h2>Semester-List</h2>

<p>
    @Html.ActionLink("Create New", "AddTerm", null, new { @class = "btn btn-primary" })
</p>
<table class="table table table-bordered" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TermName)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TermName)
            </td>
         
             <td>

                <a href="@Url.Action("EditTerm","Term" , new {id = item.id  })" class="btn btn-danger">
                    <span class="fas fa-edit mr-2"></span>

                </a>
                |
                <a href="@Url.Action("EditTerm","Term" , new {id = item.id })" class="btn btn-danger">
                    <span class="fas fa-trash mr-2"></span>

                </a>
                |
                <a href="@Url.Action("EditTerm","Term" , new { id = item.id })" class="btn btn-danger">
                    <span class="fas fa-list mr-2"></span>

                </a>



            </td>
        </tr>
        }

    </tbody>

</table>
@section scripts
{

    <script>
      $(document).ready(function () {
          $('#myTable').DataTable();
      });</script>}